### ISSUE TITLE
should the github org just be "beerjs"?

### ISSUE THREAD

**Issue by mjpizz** [beerjs/paloalto#1]
could even do one repo per location, e.g. `beerjspaloalto/beerjspaloalto` --> `beerjs/paloalto`.  Might encourage the communities to be more tied together.  idk who manages the main beerjs domain/twitter, probably could talk to them

Just a sleepy late-night thought... :waning_crescent_moon: :zzz:

**Comment by mohsen1** [comment]
I agree 
/cc @cramforce

**Comment by potch** [comment]
seems like a potentially fabulous idea. :ship:

**Comment by cramforce** [comment]
Indeed! We use http://www.meetup.com/beerjs/ but having a directory may be neat. There is also https://twitter.com/beerjs

**Comment by junosuarez** [comment]
I renamed the org & repo and gave @cramforce owner rights to the org.

We're now at https://github.com/beerjs/paloalto

I'd love to see other local groups get repos as well.

**Comment by voodootikigod** [comment]
me too pls :)

On Sun, Jun 2, 2013 at 4:24 PM, Jason Denizac notifications@github.comwrote:

> I renamed the org & repo and gave @cramforcehttps://github.com/cramforceowner rights to the org.
> 
> We're now at https://github.com/beerjs/paloalto
> 
> I'd love to see other local groups get repos as well.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/beerjs/paloalto/issues/1#issuecomment-18813119
> .

## 

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod |
GitHubhttp://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
PromoteJS http://promotejs.com/ | Minute With http://minutewith.com/

Help me end the negativity on the internet, share
thishttp://jsconf.eu/2011/an_end_to_negativity.html
.
