### ISSUE TITLE
Decembeer.js

### ISSUE THREAD

**Issue by potch** [beerjs/paloalto#10]
- **When**: Thursday, December 5th 2013, 6:30pm
- **Where**: [The Rose and Crown](http://www.yelp.com/biz/the-rose-and-crown-english-food-and-ale-house-palo-alto)
- **Who**: JavaScript enthusiasts, and those who love them
- **Why**: It's been a while, eh?
- **How**: [With a glass raised to toast your health!](http://www.youtube.com/watch?v=Bpb9EbmvM5M#t=41s)

Hope to see you there!

**Comment by derek** [comment]
In!

**Comment by lakenen** [comment]
Probably in!

**Comment by terinjokes** [comment]
Might be in

**Comment by wamatt** [comment]
maybe

**Comment by potch** [comment]
![decembeerjs-nq8](https://f.cloud.github.com/assets/253470/1676574/bb642ddc-5d1b-11e3-894a-90026ac6f459.png)

**Comment by terinjokes** [comment]
You've ordered the stickers in time for the meetup, right?

**Comment by potch** [comment]
I wish :( We'll have to have another one in a week or two!

**Comment by potch** [comment]
We are here!  At a table up front.
