### ISSUE TITLE
Janu-ale-y

### ISSUE THREAD

**Issue by potch** [beerjs/paloalto#11]
- **When**: TBD
- **Where**: [The Rose and Crown](http://www.yelp.com/biz/the-rose-and-crown-english-food-and-ale-house-palo-alto)
- **Who**: JavaScript enthusiasts, and those who love them
- **Why**: Happy New Beer.js!

New Year, new commissioner of BeerJS Palo Alto. Greetings! I'm taking a poll of what days work best for scheduling these meetups, and naturally I'd like your input.

January BeerJS: http://doodle.com/qtbuz675ph4xenev

This is a poll of what days would work for scheduling a BeerJS for this month, since the month is already started.

Future Meetups: http://doodle.com/a2qvbztz2dr7hn5m

This is a poll, using February as a template, of what days work well for a BeerJS Palo Alto meetup.

Hope to see all of you at a future event!

~Potch

**Comment by terinjokes** [comment]
So, uhm.
