### ISSUE TITLE
March meetup?

### ISSUE THREAD

**Issue by koddsson** [beerjs/paloalto#12]
Will there be one? I'm in the area and would love to meet people and drink beer ^^

**Comment by mohsen1** [comment]
+1

**Comment by nathantsoi** [comment]
I'm down

**Comment by terinjokes** [comment]
I asked for the meetup organizer bit from @potch a few weeks back, but I'm happy to go ahead with a date sometime this month either way.

What day works best? The traditional day of this meetup, from back in in 2013, is Monday or Tuesday, starting between 6 and 7. I'm good with the 23, 24, 30, or 31.

**Comment by koddsson** [comment]
The 23rd is the same day as the [Docker hackathon in Los Altos](http://www.meetup.com/Docker-Mountain-View/events/220936150/) so that might be a bad day, otherwise I'm down.

**Comment by mohsen1** [comment]
I'll be out from 27th

**Comment by terinjokes** [comment]
24th then? @jden @paulirish

**Comment by mohsen1** [comment]
24th works for me

**Comment by junosuarez** [comment]
Anyone wanna take over as admin for this group? Open an issue in https://github.com/beerjs/meta

**Comment by terinjokes** [comment]
I'm happy to, to keep this thing happening, but I'm up in SF. Someone local would be much better. :space_invader:

**Comment by terinjokes** [comment]
Tuesday, March 24th, 2015
Starts between 6pm and 7pm.

Meeting at the usual place:

[Rose and Crown (map)](https://maps.google.com/maps?q=547+Emerson+St,+Palo+Alto,+CA)
547 Emerson St
Palo Alto, CA 94301

Please RSVP or ask questions in a comment.

**Comment by koddsson** [comment]
I'll be there if you wanna ask me about javascript in Iceland! :P

**Comment by mohsen1** [comment]
Just added it to my calendar. Will be there 🍻

**Comment by koddsson** [comment]
Running late but on my way now!

**Comment by mohsen1** [comment]
Oh I added it to my calendar for March 26th. I'm in San Jose right now :(

**Comment by terinjokes** [comment]
I'm on my way.

**Comment by terinjokes** [comment]
I've made it.

**Comment by koddsson** [comment]
I am here as well! :beer:
