### ISSUE TITLE
It's hard to find people who came for beerjs in the bar

### ISSUE THREAD

**Issue by mohsen1** [beerjs/paloalto#2]
Everytime I go to a beer.js it takes 30 minutes to identify people who came for the event. It's even harder for first-timers.

**Comment by junosuarez** [comment]
I agree. Any ideas on how we can do this better? The place is usually already pretty crowded by 7. I usually make a point to try to wear some sort of JavaScripty shirt or conference shirt or something for visibility.

**Comment by mjpizz** [comment]
Definitely experienced this too.  Maybe a simple update over twitter when you find a table / area to stand?

Could also go the ridiculous-prop route...[tabletop pirate flag](http://www.amazon.com/Pirate-Banner-Plastic-Quality-Polyester/dp/B00C3L0IJ2/ref=sr_1_fkmr0_1?ie=UTF8&qid=1370190472&sr=8-1-fkmr0&keywords=mini+pirate+flag+tabletop)?

**Comment by orion11** [comment]
i'll start putting the beerjs stickers on my back and forehead so its pretty clear.  we can also make a sign for the table that says "here for beerjs" or just "here for bjs" for short.

**Comment by terinjokes** [comment]
:thumbsup:

**Comment by junosuarez** [comment]
Solved by having a critical mass of people talking about internet-y things, some of whom will recognize each other.

**Comment by terinjokes** [comment]
There's suggestion that we get a JS flag, I support this plan.
