### ISSUE TITLE
june.js - 2013-06-11

### ISSUE THREAD

**Issue by junosuarez** [beerjs/paloalto#3]
Meeting at the usual place:

7pm
[Rose and Crown (map)](https://maps.google.com/maps?q=547+Emerson+St,+Palo+Alto,+CA)
547 Emerson St
Palo Alto, CA 94301

Please RSVP or ask questions in a comment.

**Comment by potch** [comment]
I'm in!

**Comment by paulirish** [comment]
:beers:

**Comment by potch** [comment]
Isn't pub trivia normally on Tuesdays? Could be crazy busy.

**Comment by terinjokes** [comment]
Tentative yes :sparkles:

**Comment by junosuarez** [comment]
Yep, Tuesday is pub trivia day. Doesn't start til a bit later though, so we can stake out space. Rose & Crown is usually a good time.

**Comment by orion11** [comment]
woohoo we're doin it on trivia night! :) think of an awesome trivia team name.. last time I was there the winning team was "phallic baldwin"

**Comment by jeffjo** [comment]
Hey guys - it'll be my first time attending the meetup. Look forward to meeting you. Possible team trivia names: "The Char Stars" or "The Irregular Expressions" ;)

**Comment by reid** [comment]
Tentative yes! Will be there after 7:30 if I can make it!

**Comment by mjpizz** [comment]
thinkin...yes. :beer: :+1:

**Comment by davidjeon** [comment]
I'm in!

**Comment by junosuarez** [comment]
Quick reminder, this is coming up tomorrow evening. Feel free to drag a friend along if they're legit.

**Comment by mattbaker** [comment]
That's right down the block! I'll try and get a few of us over there.

**Comment by TravelingTechGuy** [comment]
@jden what is a "legit friend"? :)
Will try to make it - missed several in a row.. :(

**Comment by derek** [comment]
@TravelingTechGuy A friend who is not not legit.

**Comment by junosuarez** [comment]
yeah, @derek's right, in JavaScript you have to deal with some funky truthiness coercion, so maybe something like `bring(friends.filter(function (friend) { return !!friend.legit })`

**Comment by TravelingTechGuy** [comment]
Can you specify the reflex for legit? :)

**Comment by mattbaker** [comment]
Isn't `legit()` just a threshold function that operates on the `valueOf` a friend?

**Comment by mohsen1** [comment]
`SyntaxError: Unexpected token }`

**Comment by TravelingTechGuy** [comment]
So, you're claiming it's as simple as
`legit = function(){ return this.age >= 21; }`
?

**Comment by mattbaker** [comment]
Legitimacy is in the eye of the implementer!

**Comment by philogb** [comment]
Here's my legit code `35946533..toString(36)`! Will try to make it tomorrow, have you solved issue #2 yet? I'll be wearing glasses, hope that helps you in finding the table.

**Comment by mjpizz** [comment]
man...sad to miss this, but I'd be more sad missing some old friends that are in town at WWDC, so I'm gonna have to bow out.

also, @philogb++ for best legit implementation, would buy again

**Comment by TravelingTechGuy** [comment]
@philogb ++ - me likey!

**Comment by junosuarez** [comment]
@TravelingTechGuy yeah, send a PR to the California Code if you wanna get that changed for a future version of beer.js

@philogb that's a potential security vulnerability - good find!

@mjpizz bummer, you should file an issue for July :)

**Comment by philogb** [comment]
I won't make it today, I'm stuck here in SF... I'll be there next time!

**Comment by cvan** [comment]
omw! :train2:

**Comment by junosuarez** [comment]
omw. Re #2 , I'll be wearing a bright yellow t-shirt and my black nodepdx hoodie.

**Comment by paulirish** [comment]
Heading there now
Bringing Brendan Kenny of http://extremelysatisfactorytotalitarianism.com/blog/

:santa:

**Comment by terinjokes** [comment]
We're standing at the first window inside by the bar.

**Comment by terinjokes** [comment]
We're moving to the back corner by the dart board

**Comment by potch** [comment]
Sike! Outside in the back.

**Comment by mattbaker** [comment]
I came down with a cold and had to bow out — next time!

**Comment by junosuarez** [comment]
Thanks for coming down, you all!
