### ISSUE TITLE
Any interest in a South Bay Nodebotsday July 27th?

### ISSUE THREAD

**Issue by junosuarez** [beerjs/paloalto#5]
This upcoming July 27th is International Nodebots Day - which you can read about at [nodebotsday.com](http://nodebotsday.com). There's one organized for the city already, but I wanted to gauge interest on doing a satellite event down in the South Bay.

I participated in the Voxer Node Hardware Hack Day last fall, and it was an absolute blast. If you're curious what all the noise is about programming robots in node.js, this event is a great 1-day opportunity to get your hands dirty and have some fun.

/cc @crabdude

**Comment by terinjokes** [comment]
I would be interested.
