### ISSUE TITLE
August beer.js - August 5th

### ISSUE THREAD

**Issue by terinjokes** [beerjs/paloalto#7]
Monday, August 5th
starts between 6pm and 7pm

Meeting at the usual place:

[Rose and Crown (map)](https://maps.google.com/maps?q=547+Emerson+St,+Palo+Alto,+CA)
547 Emerson St
Palo Alto, CA 94301

Please RSVP or ask questions in a comment.

**Comment by reid** [comment]
Sounds good to me!

**Comment by junosuarez** [comment]
August 5th it is - @terinjokes I'm going to go ahead and edit your initial comment in this thread

**Comment by terinjokes** [comment]
@jden I was planning on bothering you in person tomorrow about this ticket. :+1:

**Comment by junosuarez** [comment]
Hey, that's today!

**Comment by terinjokes** [comment]
Looking forward to it!

**Comment by TravelingTechGuy** [comment]
Hi guys. Sadly, can't attend today :(
But I have a question I would have asked tonight: does anyone know of a way to run automatic tests, using a headless browser (i.e. PhantomJS, Selenium) that can also load plugins/addons? More specifically, I'd like to simulate the effects of ad-blockers (like Ghostery, ad-block+) on my code?
Cheers

**Comment by mohsen1** [comment]
The best I can recommend is [JSTestDriver](https://code.google.com/p/js-test-driver/wiki/GettingStarted) that uses actual browser so you can install plugin. You can also use CasperJS to mimic plugin behaviors by injecting plugin javascripts into your page. But that would be hard since Chrome treats plugin javascripts differently and there is a lot of chrome APIs that those plugins use.

**Comment by junosuarez** [comment]
@TravelingTechGuy agreed, something that's running in the actual browser would be best. I'm partial to [testem](https://github.com/airportyh/testem). Bonus points if you use something like Vagrant to run it in a fully virtualized and reproducible environment.

**Comment by TravelingTechGuy** [comment]
Thanks @mohsen1 and @jden - will look into JSTestDriver and the other solutions. Just thought of something: ad-blockers basically operate by blacklisting known urls. Maybe there's a way to still use PhantomJS, just firewall those urls - sort of server-side ad-block.

**Comment by terinjokes** [comment]
Thanks for everyone for showing up. I'm looking forward to seeing you all again next month, if not sooner.
