### ISSUE TITLE
September beer.js — September 17th

### ISSUE THREAD

**Issue by terinjokes** [beerjs/paloalto#8]
Tuesday, September 17th,
Starts between 6pm and 7pm.

Meeting at the usual place:

[Rose and Crown (map)](https://maps.google.com/maps?q=547+Emerson+St,+Palo+Alto,+CA)
547 Emerson St
Palo Alto, CA 94301

Please RSVP or ask questions in a comment.

**Comment by junosuarez** [comment]
How's Tuesday the 17th look?

**Comment by terinjokes** [comment]
I'll be flying in earlier that day from Arizona, but I should be able to make it.

**Comment by terinjokes** [comment]
Since there was no complains against it, editing the original post to make it the 17th

**Comment by junosuarez** [comment]
:+1: I'll make the event on meetup sometime today

**Comment by junosuarez** [comment]
http://www.meetup.com/beer-js-palo-alto/events/138645232/

**Comment by paulirish** [comment]
BEEEEEEEER

**Comment by terinjokes** [comment]
:beers:

**Comment by junosuarez** [comment]
Hey, Tuesday is also trivia night.
