### ISSUE TITLE
Jason moved to SF

### ISSUE THREAD

**Issue by junosuarez** [beerjs/paloalto#9]
Looking for a volunteer to organize future meetups. As you may have noticed if you've been to past beer.js-es, there's not a whole lot that goes into it - just a willingness to be friendly, bring people together, and help create conversation about the technology we love.

**Comment by terinjokes** [comment]
That's a lame excuse.

I'm happy to contribute, since it's one of my favorite parts of the month.

**Comment by potch** [comment]
unacceptable.

**Comment by potch** [comment]
I'm happy to organize going forward!

**Comment by junosuarez** [comment]
@potch awesome! added you as admin on the repo

**Comment by mjpizz** [comment]
^ I find this decision acceptable...in fact, more than acceptable :smiley_cat:
